# Generated by Django 5.2.5 on 2025-08-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='کلید API')),
                ('endpoint', models.CharField(max_length=100, verbose_name='نقطه پایانی')),
                ('method', models.CharField(max_length=10, verbose_name='متد HTTP')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('response_time', models.FloatField(verbose_name='زمان پاسخ (میلی\u200cثانیه)')),
                ('status_code', models.IntegerField(verbose_name='کد وضعیت')),
                ('request_size', models.IntegerField(default=0, verbose_name='اندازه درخواست (بایت)')),
                ('response_size', models.IntegerField(default=0, verbose_name='اندازه پاسخ (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
            ],
            options={
                'verbose_name': 'استفاده از API',
                'verbose_name_plural': 'استفاده\u200cهای API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام زبان')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد زبان')),
                ('native_name', models.CharField(blank=True, max_length=100, verbose_name='نام بومی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='متن ورودی')),
                ('confidence_score', models.FloatField(verbose_name='میزان اطمینان')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='زمان پردازش (ثانیه)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تشخیص')),
                ('text_length', models.IntegerField(default=0, verbose_name='طول متن')),
                ('word_count', models.IntegerField(default=0, verbose_name='تعداد کلمات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('detected_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.language', verbose_name='زبان تشخیص داده شده')),
            ],
            options={
                'verbose_name': 'تاریخچه تشخیص',
                'verbose_name_plural': 'تاریخچه تشخیص\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='نسخه مدل')),
                ('accuracy', models.FloatField(verbose_name='دقت مدل')),
                ('training_samples', models.IntegerField(verbose_name='تعداد نمونه\u200cهای آموزشی')),
                ('training_time', models.FloatField(verbose_name='زمان آموزش (ثانیه)')),
                ('parameters', models.JSONField(default=dict, verbose_name='پارامترهای مدل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=False, verbose_name='مدل فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آموزش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آموزش دهنده')),
            ],
            options={
                'verbose_name': 'لاگ آموزش مدل',
                'verbose_name_plural': 'لاگ\u200cهای آموزش مدل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('correct', 'صحیح'), ('incorrect', 'نادرست'), ('partially_correct', 'نسبتاً صحیح')], max_length=20, verbose_name='بازخورد')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازخورد')),
                ('correct_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.language', verbose_name='زبان صحیح')),
                ('detection_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionhistory', verbose_name='تاریخچه تشخیص')),
            ],
            options={
                'verbose_name': 'بازخورد کاربر',
                'verbose_name_plural': 'بازخوردهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
    ]
